### ISSUE TITLE
Issue running tests

### ISSUE THREAD

**Issue by joshi-bharat** [VIS4ROB-lab/HyperVariables#14]
I followed the instructions in the installation. I am getting issues with tests.

HyperVariables/include/hyper/variables/sensitivity.hpp:32:61: error: ‘const class hyper::variables::SensitivityBase<hyper::variables::Sensitivity<double, 3> >’ has no member named ‘reshaped’
   32 |   [[nodiscard]] inline auto asMatrix() const { return this->reshaped(kOrder, kOrder); }

HyperVariables/include/hyper/variables/se3.hpp:277:15: error: ‘setUnit’ has not been declared in ‘hyper::variables::Base<hyper::variables::SE3<double> >’
  277 |   using Base::setUnit;

I beleive the issue is some macros using  Eigen not being registered. I have just started looking at the code base. Can you help me fix this.

**Comment by joshi-bharat** [comment]
Had to upgrade to Eigen 3.4 from the source. Maybe you should update the install instructions docs.

**Comment by McEmzi** [comment]
Thanks for letting us know! Did the problem occur in Ubuntu 22.04? If not, this might be due to the fact that we only test on 22.04. I believe that Eigen 3.4.0 is the default version there.

**Comment by joshi-bharat** [comment]
I have not tested with 22.04. However, I believe it should work.
